package:
  name: iozone
  version: "3.471"

source:
  url: http://www.iozone.org/src/current/iozone3_471.tar
  sha256: 2dd29703c251044513069e0fdad0205e117ba846a0b54b45a93a684eda58c370

requirements:
  build:
    - gcc_linux-64
    - make

  run:

test:
  commands:
    - iozone -h

about:
  home: